src/lib.rs

There are three commits in this patch; only the first is material. The other two may be removed or kept at your discretion.
Currently, the following code fails to compile:
```rust
use roxmltree::{Document, Node};
pub struct Manifest<'src> {
xml: Document<'src>,
}
impl<'src> Manifest<'src> {
pub fn root_node(&self) -> Node<'_, 'src> {
self.xml.root_element()
}
}
```
because of lifetime mismatches. However, the *equivalent* code,
```rust
impl<'src> Manifest<'src> {
pub fn root_node(&self) -> Node<'_, 'src> {
self.xml.root().first_element_child().unwrap()
}
}
```
*does* compile.
This is because the definitions of `Document::root` and `Node::first_element_child` explicitly thread lifetimes, but the definition of `Document::root_element` does not. This causes the compiler to incorrectly attach …

Resolve lifetime error in `Document::root_element`

---

src/lib.rs

This commit adds unconstrained input lifetimes to the name parameters
passed in to the attribute lookup functions, so that the search text
does not need to be coupled to the lifetime of the XML parsed structures
being searched. Because the search text is only used for the duration of
the function call, and does not escape in the returned value, the search
term does not need to match the parsed lifetime.

Use unconstrained lifetimes for the `attribute` functions

---

README.md
benches/xml.rs
src/lib.rs
src/parse.rs
tests/api.rs

Hi again!
Since a roxmltree document is read-only, it seems like there are some fairly safe ways that we can take advantage of the order of `NodeId`, since their relationships should never change over the lifetime of the tree. I've made this PR as an example to start a discussion of what benefits that might be drawn from guaranteeing that `NodeId` represents the order of the document.
Some benefits:
1. Implementing the `Ord`/`PartialOrd` traits for depth-first order is trivial. If `Hash` is also implemented for Node, then it can potentially be stored in collections like `BTreeMap`, which could be helpful for anyone making complex selections in a document or for anyone writing selection languages that work on a roxmltree document (I know xpath implementation is a non-goal of this project, …

Idea: Guarantee NodeId is in document order

---

src/lib.rs

This will allow `Node` structs to be stored in some frequently used collections like `HashMap` and `HashSet`.

Impl Hash for Node

---

src/lib.rs

I expect to get some pushback on this, but currently this is the last thing that I need (for my use case) to use a fork of roxmltree for, instead of using this branch, so I would be upset with myself if I didn't try a PR :)
**Contents**
This PR add three methods:
1. `Document::nth_node` - which takes a usize `n` and returns the Node at `n` in document-order
2. `Node::order_in_document` - which is the reverse operation of `Document::nth_node`, returns the usize `n` for which `Document::nth_node` returns this node
3. `Document::len` - which returns the number of nodes in the document. I don't really care too much about this one, but it seemed related and currently the quickest way to get this value with the public API is `doc.descendants().count()`, which is a bit odd. I used this method …

Expose NodeId

---

src/parse.rs

I believe this is strictly better or equal memory efficiency to master and does not require a breaking change.
_Peak Memory Usage in MB_
| | Master | This Branch |
|----------------------------------------|--------|-------------|
| large.plist (no root namespace)        | 9.8    | 9.8       |
| large.plist (with root namespace)      | 10.6   | 9.8       |
| large.plist (2 root namespaces)        | 11.3   | 9.8       |
| large.plist (3 root namespaces)        | 12.8   | 9.8        |
| | |
| book.xhtml (12 MB + 2 root namespaces) | 217.4  | 121.4       |
| book.xhtml (4 root namespaces)         | 313.4  | 121.4       |

Reduce duplication in Namespaces

---

src/lib.rs
tests/api.rs

This PR adjusts the lifetime of `ExpandedName::name` to return a string that is bound to the lifetime of the input and not to the lifetime of the ~~`ExpandedName`~~ `ExpandedNameOwned` struct. I've added a test to illustrate an (artificial) use-case that is fixed with this PR:
```rust
fn get_tag_name<'a, 'input>(node: &'a Node<'a, 'input>) -> &'input str {
node.tag_name().name()
}
```
This method would not compile without this PR, it would fail with the following error:
```
error[E0623]: lifetime mismatch
--> tests/api.rs:290:9
|
289 |     fn get_tag_name<'a, 'input>(node: &'a Node<'a, 'input>) -> &'input str {
|                                       --------------------     -----------
|                                       |
|                                       this parameter and …
```

Adjust lifetime of name in ExpandedName

---

Cargo.toml
src/parse.rs

Hello,
I'm an active user of this crate. In my current project I need a way to compare the errors returned from the XML tree parsing. To enable this, I created this PR.
This commit additionally derives the equality-related traits. Therefore errors can now be compared. As this is a auto-derive, no tests were added.
__Note__: this is blocked by https://github.com/RazrFalcon/xmlparser/pull/12, as the underlying `xmlparser::Error` has to have the same traits as well. That PR has to be accepted and the dependency version number has to be increased before merging this.

Make `roxmltree::Error` compare-able

---

src/lib.rs

Now, `ExpandedName<'n, 'm>` can have arbitrary `'n` and `'m` lifetimes.
I also renamed the second lifetime of `ExpandedName` from `'input` to `'b`, as the `name` field might not always point to the XML input data.
Fixes https://github.com/RazrFalcon/roxmltree/issues/36

Fix lifetimes when using `ExpandedName` as parameter.

---

src/lib.rs

Also enable lint `elided_lifetimes_in_paths` (warn).

Fix returned lifetime of `Document::descendants()`.

---

README.md

https://gitlab.com/xmpp-rs/xmpp-rs/-/tree/master/minidom-rs no longer exists. The new repository appears to be https://gitlab.com/xmpp-rs/xmpp-rs/-/tree/main/minidom.

README.md: fix minidom link.

---

src/lib.rs
src/parse.rs

This my stab at the item mentioned in #63 and I have to admit that I am bit out of my depth here meaning that I wrote this based on reading the code and running the tests, not based on a actually understanding the XML processing parts. This is why I added the redundant tracking first, asserting that it would be equivalent to the in-node data and only in the last commit actually removed the `ExpandedOwnedName::prefix` field.
With this in mind, I am sorry if this is completely bogus, especially the second commit as I am unable to argue why there should be no branching, I just did never observe this during the tests.

RFC: Track parent prefixes using a stack to drop ExpandedNameOwned::prefix 

---

.github/workflows/main.yml
Cargo.toml
examples/print_pos.rs
src/lib.rs
src/parse.rs
tests/api.rs

Few things I am unsure about:
- Did I find all of them and is a compile-time feature what was intended by #63?
- Should this be a default (would be mostly backwards compatible) or non-default (ecosystem automatically picks up gains) feature?
- Should `Document::text_pos_at`, `Document::input_text` and `Document::input` also be gated behind this?
- The unit tests currently work only with the feature enabled. So maybe a default feature after all or rework the tests to assert ranges only if enabled?

Hide token ranges w.r.t. original input behind feature flag.

---

src/lib.rs
src/parse.rs

This supersedes #68 and achieves the same size reduction of `ExpandedNameOwned` with any behavioural changes.

Use a custom version of Cow<'a, str> that keeps a niche availabel to reduce the size of ExpandedNameOwned.

---

README.md
benches/Cargo.toml
benches/xml.rs

This PR adds benchmarks for [libxml](https://docs.rs/libxml/latest/libxml/), a Rust wrapper for libxml2, to the benches directory.
I noticed libxml being brought up in the comparison chart in this repo's README, and thought that it wouldn't hurt to add benchmark support for it as well.
The output for the benchmarks with the added support for libxml is, on my machine, as follows.
```
running 31 tests
test large_libxml                           ... bench:   3,039,151 ns/iter (+/- 526,303)
test large_minidom                          ... bench:   4,676,869 ns/iter (+/- 874,824)
test large_quick_xml                        ... bench:   1,295,351 ns/iter (+/- 70,644)
test large_roxmltree                        ... bench:   3,770,715 ns/iter (+/- 143,998)
test large_sdx_document …
```

Add libxml to benchmark

---

src/lib.rs
src/parse.rs

This is a break out from #75 resp. #76 since it seemed unrelated.

Use named constant for XML-namespace-related prefixes.

---

src/lib.rs
src/parse.rs
tests/ast.rs

I am sorry if this is considered invasive, but since I would really like to see #75 in a release and it seemed like only cosmetics were left to do and I had some time on my hands, I went through the open items in #75 and tried to address them by amending or adding commits from the original PR.
As to the requested explanation: Instead of storing the namespace URI itself (possibly owned or as a reference into the input) within tags and attributes, this stores only the index and resolves it on-demand into the (already deduplicated) `Document::namespaces` list using the `Attribute` wrapper around `AttributeData`.
For `greater_londom.osm`, this changes reduces the peak memory consumption from 7.8 GB to 6.7 GB.

Follow-up: Use indexes for Node and Attribute Namespaces

---

src/lib.rs

The inconsistency was `PartialEq` considering `self.d` in the comparison while `Ord` did not. I don't think it would be possible for the same node ID in the same document to yield different node data so I don't think this had any effect, but it still seems unnecessary.

Fixes a typo in impl PartialEq for Attribute and an inconsistency in impl PartialEq for Node

---

src/lib.rs
src/parse.rs
tests/ast.rs

While we do not expand namespaces into attributes any more, we still store redundantly expanded namespaces as we traverse the document tree during parsing. Now that we have the interface that puts namespaces behind an indirection, we fully deduplicate them using a sorted list of indexes.
This does not improve memory consumption on `greater_london.osm` as that document does not use any namespaces, but a for a [CSW response](https://en.wikipedia.org/wiki/Catalogue_Service_for_the_Web) of 25 MB I had lying around, this does decrease memory consumption from 120 MB to 108 MB, i.e. by almost 10%.
The benchmarks are actually a mixed bag instead of regressions throughout, most likely due to the improved locality of a smaller working set:
```
name                                    master ns/iter …
```

RFC: Deduplicate namespaces

---

src/lib.rs

`Descendants` actually had the same issue. I tried to resolve this consistently, i.e. I just left out the `doc` field everywhere and delegated to the existing iterator `Debug` impls (meaning they will print the iterator state, not a sequence of values). 
Closes #87

Use consistent debug impls for the various iterators that avoid formatting the whole document.

---

src/lib.rs

Broken out of #92 as it should be uncontroversial and that PR will most likely not land due to its ergonomic costs.

Expose 'input lifetime where it is the backing lifetime.

---

src/lib.rs
src/parse.rs
tests/api.rs

Since the method has to be called explicitly, the tuple layer serves no functional purposes.
This split in API conventions has precedence in the standard library, e.g. `HashMap::retain` accepting a two-argument closure versus `impl FromIterator for HashMap` expecting key-value pairs.
cc @WhyNotHugo

Avoid redundant tuple layer for ExpandedName::from_static

---

Cargo.toml

_xmlparser_ relies on `std` by default, unless the `xmlparser/std` feature is disabled. Conditionally enable this feature depending on `roxmltree/std`.
Fixes #38.

Fix xmlparser features for no_std build

---

Cargo.toml
src/lib.rs
src/parse.rs
src/tokenizer.rs
src/tokenizer_tests.rs
tests/api.rs

To save memory this only uses a `u16` and `u8` per `Attribute`, but the tradeoff is that the qname and value ranges will be incorrect in a few extreme data cases, specifically if the attribute's qname has len > 65535 or there are >254 spaces surrounding its equal sign.  Those cases seem unlikely enough in practice to justify not using more memory for this.

Add `range_qname` and `range_value` methods to `Attribute`.

---

README.md

We have been happily using `serde-roxmltree` in addition to the native API for our XML parsing needs for quite some time now and I have recently added opt-in support for namespaces, so by now I feel like `serde-roxmltree` can be a useful way to reduce the boiler plate of the iterator-based API when deserializing simple documents.
Hence I think it would be helpful to make potential users of this crate aware of the "add-on" crate. Of course, I understand if you want to avoid playing favourites or being associated with a crate which you do not control, hence the RFC moniker.

RFC: Add note on availability of serde-roxmltree as an additional API layer.

---

src/lib.rs

After parsing, nothing in the public API actually accesses `sorted_order` which is only used to deduplicate namespaces encountered during the parsing process. Hence, we can free the memory immediately after parsing.

Drop sorted_order after parsing as it is not used anymore

---

src/parse.rs
tests/ast.rs
tests/files/entity_err_010.xml
tests/files/entity_err_010.yaml

It would be preferable if the entity chunk itself were rejected as unbalanced as lxml does, but I think this would require tracking additional state for the current entity chunk and therefore I decided to handle only the fallout.
(Without a DTD involved, this would trigger an unknown token error from `tokenizer::parse` as the parser just sees trailing data after the last valid close tag, but with the DTD involved `tokenizer::parse_content` lacks the context that all elements have been closed.)
Closes #124

Avoid panic if entity resolution yields unbalanced tags.

---

src/parse.rs
src/tokenizer.rs

As `XmlEvents` is not public API any more, there should be no possibility of code bloat due to multiple instantiations and we can safely monomorphise dispatch from the tokenizer into the parser.
This yields small but measurable improvements in the benchmarks, but only after marking the single implementation of `XmlEvents::token` as `#[inline(always)]`, so possibly by avoiding one level of dispatching on the token type, c.f. before
```
test huge_roxmltree                         ... bench:   5,394,963 ns/iter (+/- 143,581)
test large_roxmltree                        ... bench:   2,646,532 ns/iter (+/- 19,663)
test medium_roxmltree                       ... bench:     698,086 ns/iter (+/- 70,686)
test tiny_roxmltree                         ... bench:       4,236 ns/iter (+/- 99)
```
and …

Devirtualize XmlEvents dispatch to give the optimizer full visibility
